<div
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:py="http://genshi.edgewall.org/"
	xmlns:i18n="http://genshi.edgewall.org/i18n"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	py:strip="True"
>
	<!--! XXX: Argh, a bug in v0.9.0 prevents this from ever displaying because
	           the engine is not passed to the template as it should be. -->
	<div class="form box-content" py:if="engine and engine.id">
		<p class="form_field" py:if="cloud">
			<img src="${h.url_for('/admin/images/icons/green.png')}" width="16" height="16" class="f-lft" style="margin-right:5px" />
			<strong>Panda is working</strong>: We've connected to your encoding cloud named <strong>${cloud['name']}</strong>.
			<!--! TODO: Warning: your panda cloud is tied to a different S3 bucket than the one you've configured here. ("<strong>${cloud['s3_videos_bucket']}</strong>".) -->
		</p>
		<p class="form_field" py:if="not cloud">
			<img src="${h.url_for('/admin/images/icons/red.png')}" width="16" height="16" class="f-lft" style="margin-right:5px" />
			<strong>Panda is <em>not</em> working</strong>:
			Could not connect to Panda using the below details.
		</p>
	</div>
	<xi:include href="/admin/box-form.html" />
</div>
